apply plugin: 'com.android.application'

android {
    namespace 'com.android.support'
    compileSdk 34
    ndkVersion '25.2.9519653'

    defaultConfig {
        applicationId "com.android.support"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "4.0"
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        debug {
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path file('src/main/jni/Android.mk')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
